### ISSUE TITLE
About library 

### ISSUE THREAD

**Issue by Yadavbhargav64** [controlpaths/hackbat#10]
Which are library and code should install please give us detail instructions

**Comment by rdfry** [comment]
He is only providing this as a hardware project. It is up to the makers to code it

**Comment by Zaidx1** [comment]
So there is no code available

**Comment by rdfry** [comment]
No

**Comment by MeanGreen420** [comment]
if you look in the Closed Issues section here [https://github.com/controlpaths/hackbat/issues/1](url) you will find this

Hi, this project is a HW platform. The board can be programmed using the Arduino IDE. All the peripherals except the RF have an Arduino library available so you can use it. For the RF IC, you need to modify the library from LSatan (SMARTRC-CC1101-Driver-Lib), or download the library from the repository of Joel Serna Moreno, who has a fork of the library modified for the RP2040.
