### ISSUE TITLE
Component Sourcing Issue

### ISSUE THREAD

**Issue by bfpa40** [controlpaths/hackbat#16]
I cannot seen to find a source for C14, C17 (C_0402_1005Metric) has anoyone found a suitable substitute?

**Comment by rdfry** [comment]
Try Mouser

**Comment by bfpa40** [comment]
I have and it says "No results" same for Newark but I would rather have JLCPCB source it and install them.

**Comment by MeanGreen420** [comment]
I used jlcpcb pn C513697
