### ISSUE TITLE
BOM / CPL Error @ JLCPCB

### ISSUE THREAD

**Issue by boopboopboopers** [controlpaths/hackbat#17]
The following are given when uploading BOM and CPL files.

"Error

The below parts won't be assembled due to data missing.
U5,J1,R18,R17 designators don't exist in the BOM file.
AE1 designator don't exist in the CPL file."

**Comment by SanchosPoncho** [comment]
Please refer to https://github.com/controlpaths/hackbat/issues/3

These are materials that are provide by installing the screen, NFC, and radio antenna to the board that have to completed after the fact.

**Comment by boopboopboopers** [comment]
Well, I feel like a dufus. Makes total sense. Got ahead of myself. Thanks for the response.

**Comment by bfpa40** [comment]
Whats the voltage value for Capacitor C18? Anyone know?

**Comment by controlpaths** [comment]
6.3V is enough for any capacitor.
