### ISSUE TITLE
Plastic mounting hardware for LED

### ISSUE THREAD

**Issue by bfpa40** [controlpaths/hackbat#19]
Any suggestions on plastic hardware for mounting the LED and the NFC Board? Size Dimensions?

**Comment by rdfry** [comment]
Plastic standoffs

**Comment by bfpa40** [comment]
iN THE PICTURES THEY LOOK LIKE SCREWS AND NUTS..but what sizes?

**Comment by controlpaths** [comment]
They are M3 screws.
