### ISSUE TITLE
Layout issue?

### ISSUE THREAD

**Issue by DarthMuppet54** [controlpaths/hackbat#2]
This is excellent, many thanks for your efforts here.

I raised an order with PCBWAY for some of these to be built, and they have reported this to me:

> After checking your file, we found that there is via on pad in picture showing, may I know whether we should fill with resin or not 
> 1. Fill with resin, the cost of pcb will increase and it will be good for assembly
> 2.Without resin, when you solder SMD components on pad, then paster will be easy leak out from pad

![W706450AS1K1](https://github.com/controlpaths/hackbat/assets/60889419/e0011d2e-7491-4309-bb46-90adb6e08ed7)

 Can you advise please? 

Thanks

**Comment by controlpaths** [comment]
Hi, some PCB manufacturers ask you about vias on pads because it could be a mistake, but not in this case.
