### ISSUE TITLE
Jlcpcb question on my order - need help

### ISSUE THREAD

**Issue by bfpa40** [controlpaths/hackbat#20]
This is what they just emailed me:
Hello,
Sorry to bother you, but we'd like to confirm with you an issue found during review of your PCB order before proceeding.

As shown below,there are many files ,may we know if we can use output_files folder for PCB production ?

Your early reply will be highly appreciated, thank you so much!、

Here is a link to the screengrab not sure how to respond to them?  https://imgur.com/8zUjxvb

**Comment by VeganismTho** [comment]
I'm a noob, but from what I understand you sent them the entire list of files and not just the compressed "output files". So you can tell them yes to use the output file. I imagine your comment may have come before such advice was put into the readme. Be sure to upload the centroid and BOM file. Not that I know what the does or how to do it yet. My response is too late for you I imagine, but should anyone else stumble on this problem hopefully this helps.
