### ISSUE TITLE
Received order from JLCPCB boards not trimmed

### ISSUE THREAD

**Issue by bfpa40** [controlpaths/hackbat#24]
Just received my order from JLCPCB but it seems as though they didnt remove the excess material from the top and the bottom of the boards.. Its "scored" on both sides if you would call it that but not removed. pretty firm still wont easily snap off ive never dealt with this before what is recommended? I could exert more force and use a vice OR use a box cutter to further score to remove.. what would folks recommend?
![PXL_20240626_000618668](https://github.com/controlpaths/hackbat/assets/26695291/96b11234-d9c3-44b1-b0e5-289906baab59)
![PXL_20240626_000741855](https://github.com/controlpaths/hackbat/assets/26695291/7c914f39-ea63-4af2-b2a9-6f0f559f9440)
![PXL_20240626_000755413](https://github.com/controlpaths/hackbat/assets/26695291/71395d28-c4d6-415b-b71f-0e5697a252d5)
![PXL_20240626_000823703](https://github.com/controlpaths/hackbat/assets/26695291/0535a05b-74c9-44f2-a9d4-79662fac1e7b)
![PXL_20240626_000833157](https://github.com/controlpaths/hackbat/assets/26695291/e72cf3c0-fd30-4603-933e-4233051b5902)
![PXL_20240626_000839539](https://github.com/controlpaths/hackbat/assets/26695291/1ce4195e-6232-49db-a979-5c98f867261d)

**Comment by controlpaths** [comment]
Hi, you can break it with your hands. That part of pcb is needed for the PCB Assembly. All the assembled boards have it.
