### ISSUE TITLE
Capacitor swaps c13-17 c21

### ISSUE THREAD

**Issue by VeganismTho** [controlpaths/hackbat#25]
on the site you can search for alternatives and it gives you 1 to 5 to pick from. Will just any of the alternatives they recc work as long as it doesn't have a question mark pointing out that the part is slightly off from the one requested? Right next to select a question mark when hovered over says: 

"The part does not match the one(Comment: 3.9p Footprint: Capacitor_SMD:C_0402_1005Metric) provided in your BOM. Please confirm it."

These things are tiny, I'm hoping to avoid having to get a better solder set to put them in myself with the requested capacitors found elsewhere. Though might have to do that either way for the 5 parts or so we put on ourselves. Anyone have rec for solder set for working on these things?

I looked into a lil, seemed simple enough to swap parts out. Hopefully it works out. On to ordering the other parts.

**Comment by rdfry** [comment]
Hot air gun
