### ISSUE TITLE
RP2040 Board

### ISSUE THREAD

**Issue by thealidev** [controlpaths/hackbat#8]
Is the `RP2040` board is respary pi pico ?

**Comment by rdfry** [comment]
It's the same MCU sans the bd

**Comment by thealidev** [comment]
What do you mean?

**Comment by rdfry** [comment]
This board just uses the 2040 mcu and has nothing to do with the pico

**Comment by thealidev** [comment]
Where can i buy it
Don't say Amazon or eBay
I live in Pakistan
So i need it here for cheap

**Comment by rdfry** [comment]
Try Ada Fruit

**Comment by thealidev** [comment]
Link ...

**Comment by rdfry** [comment]
Try cytron.com

**Comment by Zaidx1** [comment]
cytron.com is not opening

**Comment by rdfry** [comment]
Sorry it's cytron.io
